// ─── PDF Export ───────────────────────────────────────────────────────────────
// Generates a styled trip itinerary PDF using jsPDF
// ─────────────────────────────────────────────────────────────────────────────
import { jsPDF } from 'jspdf';
import { calcTripTotal } from './tlStorage';

const INR = (n) => `Rs. ${(Number(n) || 0).toLocaleString('en-IN')}`;
const CAT_ICONS = { train: '🚂', car: '🚗', flight: '✈️', food: '🍽️', stay: '🏨' };
const STATUS_LABEL = { planned: 'Planned', ongoing: 'Ongoing', completed: 'Completed' };

export function exportTripPDF(trip, place) {
  const doc    = new jsPDF({ unit: 'mm', format: 'a4' });
  const W      = doc.internal.pageSize.getWidth();
  let   y      = 20;

  // ── helper functions ────────────────────────────────────────────────────────
  function text(str, x, fontSize = 11, color = [30, 30, 30], bold = false) {
    doc.setFontSize(fontSize);
    doc.setTextColor(...color);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.text(str, x, y);
  }
  function line(col = [220, 220, 220]) {
    y += 3;
    doc.setDrawColor(...col);
    doc.line(15, y, W - 15, y);
    y += 4;
  }
  function row(label, value, indent = 15) {
    text(label, indent, 10, [100, 100, 100]);
    text(value, indent + 55, 10, [30, 30, 30]);
    y += 6;
  }
  function checkPage() {
    if (y > 270) { doc.addPage(); y = 20; }
  }

  // ── HEADER ──────────────────────────────────────────────────────────────────
  // Green top strip
  doc.setFillColor(16, 185, 129);
  doc.rect(0, 0, W, 28, 'F');
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text(`${trip.emoji || '✈️'}  ${trip.name}`, 15, 18);
  y = 40;

  // Trip year + status badge
  text(`${trip.year || ''}   ·   ${STATUS_LABEL[trip.status] || trip.status}`, 15, 12, [80, 80, 80], false);
  y += 10;

  // Place info
  if (place) {
    text(`📍 ${place.name}`, 15, 11, [30, 30, 30]);
    y += 6;
    const loc = place.stateOfIndia
      ? `${place.stateOfIndia}, India`
      : `${place.country || ''}${place.continent ? ` (${place.continent})` : ''}`;
    text(loc, 15, 10, [100, 100, 100]);
    y += 8;
  }

  line();

  // ── NOTES ──────────────────────────────────────────────────────────────────
  if (trip.tripNotes) {
    text('Notes', 15, 11, [30, 30, 30], true);
    y += 6;
    const lines = doc.splitTextToSize(trip.tripNotes, W - 30);
    doc.setFontSize(10);
    doc.setTextColor(70, 70, 70);
    doc.setFont('helvetica', 'normal');
    lines.forEach(l => { checkPage(); doc.text(l, 15, y); y += 5; });
    y += 4;
    line();
  }

  // ── VISITED SPOTS ──────────────────────────────────────────────────────────
  if (trip.spots?.length) {
    text('Visited Spots', 15, 11, [30, 30, 30], true);
    y += 7;
    trip.spots.forEach(s => {
      checkPage();
      text(`📍  ${s.name}`, 18, 10, [50, 50, 50]);
      y += 6;
    });
    y += 2;
    line();
  }

  // ── EXPENSES ───────────────────────────────────────────────────────────────
  const exp = trip.expenses || {};
  text('Expense Breakdown', 15, 11, [30, 30, 30], true);
  y += 8;

  const CATS = ['train', 'car', 'flight', 'food', 'stay'];
  CATS.forEach(cat => {
    const amt = Number(exp[cat]) || 0;
    if (amt <= 0) return;
    checkPage();
    row(`${CAT_ICONS[cat]}  ${cat.charAt(0).toUpperCase() + cat.slice(1)}`, INR(amt));
  });

  (exp.activities || []).forEach(a => {
    if (!a.name) return;
    checkPage();
    row(`🎯  ${a.name}`, INR(a.amount));
  });

  y += 2;
  line([180, 180, 180]);

  // Total
  const total = calcTripTotal(trip);
  doc.setFillColor(240, 253, 248);
  doc.rect(12, y - 3, W - 24, 14, 'F');
  text('TOTAL SPENT', 15, 12, [16, 185, 129], true);
  text(INR(total), W - 55, 12, [16, 185, 129], true);
  y += 16;

  // ── FOOTER ─────────────────────────────────────────────────────────────────
  line([220, 220, 220]);
  text('Generated by TravelList · Your Personal Travel Bucket List', 15, 8, [160, 160, 160]);

  // ── SAVE ───────────────────────────────────────────────────────────────────
  const filename = `${(place?.name || 'Trip').replace(/\s+/g, '_')}_${trip.name.replace(/\s+/g, '_')}.pdf`;
  doc.save(filename);
}
