import jsPDF from 'jspdf';
import { formatCurrency } from './polarstepsStorage';

export function exportPolarstepsPDF(trip, steps = [], itinerary = [], _expenses = null) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210;
  const H = 297;

  // ── Cover Page ──
  doc.setFillColor(15, 23, 42); // Dark slate bg
  doc.rect(0, 0, W, H, 'F');

  // Decorative header gradient box
  doc.setFillColor(16, 185, 129); // Emerald accent
  doc.rect(20, 40, W - 40, 4, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text(trip?.title || trip?.name || 'Travel Log & Itinerary', 20, 60);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text(`Destination: ${trip?.destination || 'Global Voyager'}`, 20, 72);
  doc.text(`Dates: ${trip?.startDate || ''} to ${trip?.endDate || ''}`, 20, 80);

  // Stats badge on cover
  const totalKm = steps.reduce((sum, s) => sum + (s.distKm || 0), 0);
  doc.setFillColor(30, 41, 59);
  doc.roundedRect(20, 95, W - 40, 36, 4, 4, 'F');

  doc.setTextColor(16, 185, 129);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(`${totalKm.toLocaleString()} KM`, 30, 112);
  doc.setTextColor(255, 255, 255);
  doc.text(`${steps.length} STEPS`, 90, 112);
  doc.text(`${itinerary.length} DAYS`, 150, 112);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('TOTAL DISTANCE', 30, 122);
  doc.text('LOGGED STOPS', 90, 122);
  doc.text('ITINERARY DURATION', 150, 122);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by RoamWithPranit Polarsteps Travel Suite', 20, 275);

  // ── Page 2: Step Journal ──
  doc.addPage();
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, W, H, 'F');

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('📍 Logged Travel Steps & Stories', 20, 24);

  let y = 36;

  if (steps.length === 0) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(148, 163, 184);
    doc.text('No travel steps recorded yet.', 20, y);
  } else {
    steps.forEach(s => {
      if (y > 260) {
        doc.addPage();
        y = 24;
      }

      doc.setFillColor(248, 250, 252);
      doc.roundedRect(20, y, W - 40, 26, 3, 3, 'F');

      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text(`Step ${s.stepNo}: ${s.name}`, 26, y + 8);

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 116, 139);
      doc.text(`${s.date || ''} ${s.time || ''} · Mode: ${s.transportMode || 'travel'} · +${s.distKm || 0} km`, 26, y + 15);

      if (s.notes) {
        doc.setTextColor(51, 65, 85);
        doc.text(s.notes.slice(0, 80) + (s.notes.length > 80 ? '…' : ''), 26, y + 21);
      }

      y += 32;
    });
  }

  // ── Page 3: Day-by-Day Itinerary ──
  doc.addPage();
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('📅 Day-by-Day Itinerary Schedule', 20, 24);

  y = 36;
  itinerary.forEach(day => {
    if (y > 250) {
      doc.addPage();
      y = 24;
    }

    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(16, 185, 129);
    doc.text(`Day ${day.dayNum}: ${day.title}`, 20, y);
    y += 8;

    ['morning', 'afternoon', 'evening', 'night'].forEach(slot => {
      const items = day.timeSlots?.[slot] || [];
      items.forEach(item => {
        if (y > 270) {
          doc.addPage();
          y = 24;
        }

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(30, 41, 59);
        doc.text(`• [${slot.toUpperCase()}] ${item.time || ''} - ${item.name} ${item.loc ? `(@ ${item.loc})` : ''}`, 24, y);
        if (item.cost) {
          doc.setTextColor(16, 185, 129);
          doc.text(formatCurrency(item.cost), 170, y);
        }
        y += 6;
      });
    });

    y += 6;
  });

  doc.save(`${(trip?.title || 'trip').replace(/\s+/g, '_')}_Polarsteps_Book.pdf`);
}
